import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import type { ResumeContent } from "@/lib/resume/content";

/*
 * The résumé as a Word document an applicant tracking system can actually read.
 *
 * This is only possible because the structure is kept. Building a .docx from
 * the text column would mean guessing which lines were headings and which were
 * bullets, and getting that wrong produces exactly the file people complain
 * about: one where every line is a paragraph and the parser finds no sections.
 *
 * Three deliberate constraints, all of them about the machine that reads this
 * before a person does:
 *
 *   - Real heading styles, not bold text that looks like a heading. A parser
 *     looks for the style, not the weight.
 *   - Real bullet lists, not a hyphen typed at the start of a line.
 *   - One column, no tables, no text boxes, no headers or footers. Multi-column
 *     layout is the most common reason a candidate is parsed into nonsense, and
 *     contact details in a header are frequently dropped entirely.
 *
 * Times New Roman at 11pt because it is metrically ordinary and universally
 * present; a missing font substitutes unpredictably and changes the pagination.
 */

const BODY_FONT = "Times New Roman";
/** docx sizes are half-points, so 22 is 11pt. */
const BODY_SIZE = 22;

export function buildResumeDocx(content: ResumeContent): Document {
  const children: Paragraph[] = [];

  if (content.headline.trim()) {
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 160 },
      children: [new TextRun({ text: content.headline.trim(), bold: true, size: 32, font: BODY_FONT })],
    }));
  }

  if (content.summary.trim()) {
    children.push(sectionHeading("Professional Summary"));
    children.push(new Paragraph({
      spacing: { after: 160 },
      children: [new TextRun({ text: content.summary.trim(), size: BODY_SIZE, font: BODY_FONT })],
    }));
  }

  for (const section of content.sections) {
    const bullets = section.bullets.filter((bullet) => bullet.text.trim());
    /* A heading with nothing under it reads as a section the person left empty. */
    if (!bullets.length) continue;

    if (section.heading.trim()) children.push(sectionHeading(section.heading.trim()));
    for (const bullet of bullets) {
      children.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        children: [new TextRun({ text: bullet.text.trim(), size: BODY_SIZE, font: BODY_FONT })],
      }));
    }
  }

  return new Document({
    creator: "Sartho",
    description: "Résumé generated by Sartho from approved career evidence.",
    title: content.headline.trim() || "Résumé",
    styles: {
      default: {
        document: { run: { font: BODY_FONT, size: BODY_SIZE } },
      },
    },
    sections: [{
      properties: {
        page: {
          /* Twips: 1 inch margins all round, which every reviewer expects. */
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children,
    }],
  });
}

/*
 * A real Heading 1, not bold text of the same size.
 *
 * The distinction is invisible on screen and decisive to a parser: a style is
 * machine-readable structure, a bold run is a formatting accident that happens
 * to look like structure.
 */
function sectionHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 240, after: 100 },
    children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 24, font: BODY_FONT })],
  });
}

/** The document as bytes, ready to send. */
export function resumeDocxBuffer(content: ResumeContent): Promise<Buffer> {
  return Packer.toBuffer(buildResumeDocx(content));
}

/*
 * A filename somebody can find again in their downloads folder six weeks later.
 *
 * "resume.docx" is what every other tool produces, and a person applying for
 * fifteen roles ends up with resume(7).docx and no idea which one it is.
 */
export function resumeFileName(versionName: string, employer: string | null, extension: string): string {
  const parts = [versionName, employer].filter((part): part is string => Boolean(part?.trim()));
  const stem = parts.join(" - ")
    .normalize("NFKD")
    /* Windows and macOS both refuse some of these outright. */
    .replace(/[\\/:*?"<>|]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
  return `${stem || "Resume"}.${extension}`;
}
